[package]
name = "verify"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
common = { path = "../../common" }
risc0-zkvm = { version = "1.1", default-features = false, features = ["std"] }
hex = "0.4"
